version: '2.1'

services:
  meta:
    image: busybox # Necessary to make this container valid.
    environment:
      - MYSQL_USER=drupal
      - MYSQL_DATABASE=drupal
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password

  app:
    extends:
      service: meta
    image: APP_IMAGE_NAME
    build:
      context: ./docker/
      args:
        USER_ID: '$USER_ID'
        GROUP_ID: '$GROUP_ID'
    hostname: app
    ports:
      - 80:80
    cap_add:
      - ALL
    links:
     - database:database-host
    volumes:
      - $HOME/.ssh:/taller/.ssh
      - $HOME/.gitconfig:/taller/.gitconfig
      - $PWD:/taller/app
      - $PWD/temp/.bash_history:/taller/.bash_history

  database:
    extends:
      service: meta
    image: mysql:5.6
    container_name: DB_CONTAINER_NAME
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
